require('dotenv').config()
const { Pool } = require('pg')

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
})

async function migrate() {
  try {
    // Create orders table with payment account column
    const createTableSQL = `
      CREATE TABLE IF NOT EXISTS public.orders (
        order_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        account_id INTEGER NOT NULL,
        inv_id INTEGER NOT NULL,
        order_phone CHARACTER VARYING NOT NULL,
        order_address CHARACTER VARYING NOT NULL,
        order_city CHARACTER VARYING NOT NULL,
        order_state CHARACTER VARYING NOT NULL,
        order_zip CHARACTER VARYING NOT NULL,
        order_payment_account CHARACTER VARYING NOT NULL,
        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        order_status CHARACTER VARYING DEFAULT 'Pending' NOT NULL,
        CONSTRAINT orders_pkey PRIMARY KEY (order_id),
        CONSTRAINT fk_orders_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) ON DELETE CASCADE,
        CONSTRAINT fk_orders_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) ON DELETE CASCADE
      )
    `
    
    await pool.query(createTableSQL)
    console.log("✓ Orders table created with order_payment_account column")
    
    // Create indexes
    await pool.query("CREATE INDEX IF NOT EXISTS idx_orders_account_id ON public.orders (account_id)")
    await pool.query("CREATE INDEX IF NOT EXISTS idx_orders_inv_id ON public.orders (inv_id)")
    console.log("✓ Indexes created successfully")
    
    console.log("\nMigration successful!")
    await pool.end()
    process.exit(0)
  } catch (error) {
    console.error("Migration error:", error.message)
    await pool.end()
    process.exit(1)
  }
}

migrate()
