-- Migration: Add Orders table and address fields to account
-- This migration adds support for order management

-- Add address and phone fields to account table
ALTER TABLE public.account
ADD COLUMN IF NOT EXISTS account_phone CHARACTER VARYING,
ADD COLUMN IF NOT EXISTS account_address CHARACTER VARYING,
ADD COLUMN IF NOT EXISTS account_city CHARACTER VARYING,
ADD COLUMN IF NOT EXISTS account_state CHARACTER VARYING,
ADD COLUMN IF NOT EXISTS account_zip CHARACTER VARYING;

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
  order_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_id INTEGER NOT NULL,
  inv_id INTEGER NOT NULL,
  order_phone CHARACTER VARYING NOT NULL,
  order_address CHARACTER VARYING NOT NULL,
  order_city CHARACTER VARYING NOT NULL,
  order_state CHARACTER VARYING NOT NULL,
  order_zip CHARACTER VARYING NOT NULL,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  order_status CHARACTER VARYING DEFAULT 'Pending' NOT NULL,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT fk_orders_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) ON DELETE CASCADE,
  CONSTRAINT fk_orders_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) ON DELETE CASCADE
);

-- Create index on account_id for faster queries
CREATE INDEX IF NOT EXISTS idx_orders_account_id ON public.orders (account_id);
CREATE INDEX IF NOT EXISTS idx_orders_inv_id ON public.orders (inv_id);
