-- Migration: Add Shopping Cart system
-- This migration creates a cart table for multi-item shopping

CREATE TABLE IF NOT EXISTS public.cart (
  cart_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_id INTEGER NOT NULL,
  inv_id INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1 NOT NULL,
  added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cart_pkey PRIMARY KEY (cart_id),
  CONSTRAINT fk_cart_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) ON DELETE CASCADE,
  CONSTRAINT unique_user_vehicle UNIQUE (account_id, inv_id)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_cart_account_id ON public.cart (account_id);
CREATE INDEX IF NOT EXISTS idx_cart_inv_id ON public.cart (inv_id);

-- Update orders table to support multiple items per order
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS order_total_price NUMERIC(10, 2),
ADD COLUMN IF NOT EXISTS order_total_items INTEGER DEFAULT 1;
